### ISSUE TITLE
Bridge server crashes when using Python 3.7

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-bridge#103]
There is a change in Python 3.7 compared to prev versions where "async" is now a reserved keyword.

Several libraries the bridge server depends on (celery, kombu, redis) do use that keyword and need to get upgraded to fix this issue.
- celery and kombu can get upgraded to 4.2.0
- but there is no update available yet for redis (we are running latest which is 2.10.6)

For now the workaround is for developers to use Python 3.6

**Comment by tomlinton** [comment]
It looks like [celery is the issue](https://github.com/celery/celery/issues/4849) here. I think the redis package is OK for 3.7. Confusingly the error that celery spits out is in a file named redis.py.

I tested on 3.7 with an install from the development branch of celery that has the fix for this and the celery worker was fine. It looks like a minor release for celery will happen at the end of the month (i.e. we are waiting for celery 4.2.1).

**Comment by franckc** [comment]
Thanks for investigating on this @toml - nice work !
Sounds good, let’s upgrade to celery 4.2.1 when it becomes available.

**Comment by micahalcorn** [comment]
Hey, @tomlinton are you on our Discord channel? If, so what’s your name there? If not, well, join us! 😄

**Comment by tomlinton** [comment]
toml on discord :smile:

**Comment by tomlinton** [comment]
celery 4.2.1 is out but this fix didn't make it. :cry:

**Comment by tomlinton** [comment]
Closed by removal of celery in #134.
