### ISSUE TITLE
Design and stub out messaging service

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/origin-bridge#5]
Come up with high-level messaging requests and responses.

Handles messaging between two parties (buyer and seller). Lots of thinking needed here.

**Comment by joshfraser** [comment]
Our thinking has developed a bit since we wrote that, but the same high-level objectives apply. We're currently considering using IPFS pubsub chat rooms as the foundation for conversations between buyers and sellers. Everything would be encrypted of course. Instead of looping in the arbitrator from the beginning, we'd allow either the buyer or seller to reveal the message thread to an arbitrator & the arbitrator would be able to verify the accuracy of what was said by checking a chain of signatures. 

This approach would mean that we're not dependent on the bridge server for arbitration since all conversations will be stored publicly on IPFS, only encrypted. 

The specific encryption method hasn't been defined either, but the leading contenders are 1) deriving a key from the private key of your ETH wallet (more convenient than having to sign each message using Metamask) or 2) using PGP. 

It's also possible that we do something totally different once we get working on an implementation.

**Comment by ambertch** [comment]
One random idea (somewhat whacky and glossing over some stuff):

From IPFS, it looks like authentication is still being implemented for pubsub. Even without authentication as a feature, the buyer and seller can communicate securely over a given channel using their keypairs:
- the address is a hash of the public key, so it is known that the two public keys correspond to the buyer and seller accounts
- sent messages are encrypted with the public key of the message receiver
- for each party, the other party's authenticity is verified via signature

There could be a requirement that there is a record of the channel being established (in order to create an audit trail). One of the contracts could have a method to generate the channel name, although this is then readable off of the blockchain. Even with the messages being encrypted, it might be good to have the channel establishment be obfuscated.

To do this, something like Diffie-Hellman could be used. Although instead of a shared secret, what is being established is a "UUID" for the channel name. If the contract generates the DH modulus and base upon the purchase occuring and stores the intermediate state, and no soft forks occur, this can take place in 1 block time (I think?[1]), which is on an order suitable for near-realtime messaging use cases such as connected car / ridesharing.


[1] Suppose both buyer and seller are online. When the purchase happens, an event is written to the log with the modulus and base, and read by both parties. On the next cycle, the parties compute and send the intermediate values to the contract. They are written to the log, and can be read to compute the channel UUID.

**Comment by joshfraser** [comment]
@ambertch I like how you're thinking about it. Generally the right approach.

- Would it make sense for us to include the specific listing in the hash used for the channel address? (I don't think so, but worth consideration)

- What if we created a channel for every wallet? That way, if you want to message someone, you just need their wallet address. This could have broad usage even beyond Origin, but to start, we could use it to notify a user when a new shared channel has been created.

**Comment by ambertch** [comment]
@joshfraser thanks!
- RE: listing information in the channel, so I'm not sure how well the approach above can generate a true UUID, maybe using listing info would be good for generating a lower collision channel name
- RE: channel per wallet, what would mark a thread / conversation between parties? With Facebook Messenger, for instance, every thread is identified by the participants in the conversation. Also, how to mark which listing the messages are a part of?

So, listing information and wallet could be combined to uniquely identify messaging around a listing. The client would receive inbound messages on the channel, and it may also be good for the client to write outbound messages there as well (as to create a record of the conversation).

I don't think IPFS pubsub currently supports message persistence, although it looks like Orbit does 
 (https://github.com/orbitdb/ipfs-log)

**Comment by ambertch** [comment]
**Implementation Q's**

Q0: When does messaging take place? (discussion during 5/9 meeting)
	- Before the transaction, throughout transaction stages, and after the transaction

Q1: How would a messaging system be designed?
	- One option is to use events: Ex. purchase contract currently emits a PurchaseChange event, this can trigger notifications to be sent out by the bridge server to buyer and seller
	- Buyer and seller would have a client that can both receive notifications and connect to the messaging platform (whisper, public chat programs, IPFS pubsub)

Q2: How can we implement the notion of threads, like in messenger apps? (pertains to IPFS pubsub)
	- One option is to have channel names correspond to account address + information from the listing. This is a simple way for buyer, seller, arbitrator, etc. to know where the messages are.

Q3: How can we encrypt the messages?
	- One option is to use public and private keys of ethereum accounts
	- Would require customer to give an application access to their wallet keys

Q4: How can we do arbitration? 
	- The messages can be stored as well as signed, so in the event of an arbitration either party can provide both the messages and the chain of message signatures

Q5: How do we store the message logs for arbitration? (pertains to IPFS pubsub)
	- This is yet to be implemented https://github.com/libp2p/go-floodsub/issues/42
	- Orbit built a chat implementation on top of IPFS (which stores messages)
	

**Notes**

- The application isn't particularly latency sensitive, although we should measure long tail latencies (99.9, 99.99 percentile) 
	- N/A if using a public chat program

- Only 2 parties per messaging session or thread, so unlikely to run into any issues related to scale. With IPFS pubsub,
	- Current pubsub implementation is "floodsub", where publishes are broadcasted 
	- A gossip protocol (reduces write amplification via not requiring brodcasts) is being implemented (https://github.com/libp2p/go-floodsub/pull/67)

**Comment by joshfraser** [comment]
Haven't taken a look at them yet, but http://matrix.org and https://vector.im have also been mentioned as messaging solutions we should investigate.

**Comment by crazybuster** [comment]
Currently I'm implementing "Q1", which broadcast events emitted by the listing and purchase contracts. My naive implementation is in the logic/notifier_service.py this services just listens for events that are processed to the indixer_service and fires of notifications to endpoints that are registered to the relevant eth_address. The device implementations for displaying the notifications are still pending(done in react native currently). This of course is only for public notifications and not for secure messaging between buyer and seller.

Having to give access to message logs for arbitration really changes the scope of this. If we do want this to persist, then maybe a ipfs chatroom might be a better option. How would an arbitrator get access to the logs, are they established beforehand?

**Comment by micahalcorn** [comment]
Here is the mess of an architectural diagram that I showed in today's engineering call. @DanielVF would have been proud. ![origin dapp messaging](https://user-images.githubusercontent.com/273937/42004538-163f968a-7a25-11e8-8067-0261adb3f710.jpeg)
Again, the complexity arises because we are trying to make a messaging service that is

a) encrypted and secure
b) auditable under certain circumstances
c) as decentralized as possible

I am working on a document with product specs and will post that here soon. The engineering implementation will certainly evolve as @crazybuster continues to experiment.

**Comment by micahalcorn** [comment]
Here is the draft outlining the implementation:

https://docs.google.com/document/d/1TnjTIBCA0VWoCmlHgmXwCL07m2RlHHJ8pGAWhF5BQeA

**Comment by micahalcorn** [comment]
Considering this done though not yet merged ✅
