### ISSUE TITLE
Syncing origin-js and bridge server for local instances

### ISSUE THREAD

**Issue by crazybuster** [OriginProtocol/origin-bridge#68]
It'd be good to have somewhere, some tag/version mapping of which version of origin-js the contracts of bridge server is built again. If not, there could be definitely be mismatches of what contracts are running on origin-js and what the bridge-server is listening for. 

Not at all sure what this should look like. Maybe just an entry in the README? We don't have a monolithic run script.

**Comment by ambertch** [comment]
In addition to the contract ABIs, the listing schemas are also pieces of data that will require versioning... there will probably be cases where two versions aren't backwards compatible (like major and minor versions of software).

Since this data is also used by multiple components (currently origin-js, bridge server, dapps) there could be the need for a synchronization mechanism in the future.

**Comment by franckc** [comment]
The plan is to write an "EventListener" in Node.js that integrates with origin-js library.
Work is being tracked in [here](https://github.com/OriginProtocol/origin-js/issues/290).

Closing this issue.
