### ISSUE TITLE
Pagination: Listings

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-bridge#99]
A request for all listings should not actually yield all of them. There should be a default limit (maybe 10?) with a maximum limit (maybe 100?). Other parameters might include the starting position and/or ending position for the "page" and the response should probably indicate whether or not there are more results to retrieve in a subsequent request.

**Comment by lucadgtrip** [comment]
just as a data point the main platforms have moved away from the standard 10 listings per page to: 
- 18: Airbnb
- 20: Booking
- 31: Tripadvisor
- 50: Homeaway
(funnily enough the more successful have less listing per page, the struggling ones have more)

**Comment by franckc** [comment]
Here is the relevant Flask restless documentation regarding pagination:
https://flask-restless.readthedocs.io/en/stable/requestformat.html#pagination

Currently our listing, purchase and review Flask Restless endpoints have a fixed page size of 10 entries. See https://github.com/OriginProtocol/origin-bridge/blob/develop/app/app_config.py#L41

I'd suggest we change the current behavior for listing, purchase and review endpoints to the following:
 - By default, have server return 10 entries per page
 - Let the DApp pass an optional "results_per_page" argument to specify a different value if needed. Cap that value to a maximum of 100 items by setting max_results_per_page on the server side.

Tagging issues #100 and #101 since this comment is relevant to those.

**Comment by sparrowDom** [comment]
See the solution here: 
https://github.com/OriginProtocol/origin-bridge/pull/129

And all that was needed were 3 lines of code.
